1 start
Soft-Atom/dz-react pull request #1
Opened 2024-09-23 16:30 UTC by Soft-Atom

2024-09-28 15:49 UTC, Webappmaster-Eugene requested changes
Пару изменений всего лишь внести, в целом все неплохо!

2024-09-28 15:49 UTC, Webappmaster-Eugene commented on src/entities/movie/movie.contracts.ts
> +	// тут должен быть масив енам
Так, а почему не сделаешь енам?

2024-09-28 15:49 UTC, Webappmaster-Eugene commented on src/shared/ui/anchor/interfaces/props.interface.ts
> +export interface IProps extends AnchorHTMLAttributes<HTMLAnchorElement> {
Лучше ты тут никак не сделаешь. Честно говоря, я бы и не стал до таких деталей погружаться, этой типизации уже достаточно

2024-09-28 15:49 UTC, Webappmaster-Eugene commented on src/shared/ui/icon/icon.shared.tsx
> +import styles from './styles.module.css';
Если стили пустые, тогда смысл импортить?

2024-09-28 15:49 UTC, Webappmaster-Eugene commented on src/shared/ui/paragraph/interfaces/index.ts
> +export * from './/paragraph-size.type.ts';
импортишь неправильно

2024-09-28 15:49 UTC, Webappmaster-Eugene commented on src/wigets/header/header.widget.tsx
> +								// icon={<></>}
удалить

2024-09-28 15:49 UTC, Webappmaster-Eugene commented on src/wigets/movie/movie-list/movie-list.widget.tsx
> +export function MovieList({}: IProps) {
Тоже, в чем смысл оставлять пустое?

2024-09-29 13:33 UTC, Soft-Atom commented on src/entities/movie/movie.contracts.ts
> +	// тут должен быть масив енам
Потому что я не знаю всех  значений) погружаться в это дело долго))

2024-09-29 13:33 UTC, Soft-Atom commented on src/entities/movie/movie.contracts.ts
> +	// тут должен быть масив енам
есть где-то дока по этому api?

2025-01-16 09:20 UTC, merged